"""Sample data model for prompt-response pairs."""

from pydantic import BaseModel, Field
from datetime import datetime, timezone
from typing import Dict, Any


class Sample(BaseModel):
    """Represents a prompt-response pair to be annotated.
    
    Attributes:
        id: Unique identifier for the sample
        prompt: Input text sent to the LLM
        response: Output text generated by the LLM
        metadata: Flexible dictionary for additional context (model, task_type, etc.)
        imported_at: Timestamp when sample was imported into the system
    """
    id: str = Field(..., description="Unique identifier for the sample")
    prompt: str = Field(..., description="Input to the LLM")
    response: str = Field(..., description="LLM's output")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Flexible metadata (model, task_type, etc.)"
    )
    imported_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "sample_001",
                "prompt": "What is the capital of France?",
                "response": "The capital of France is Paris.",
                "metadata": {
                    "model": "gpt-4",
                    "task_type": "factual_qa"
                }
            }
        }

